tango_with_django_project/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
    ]

tango_with_django_project/rango/urls.py
from django.urls import path
from rango import views
from rango.views import AboutView, AddCategoryView
from rango.views import ProfileView


app_name = 'rango'
urlpatterns = [
    path('', views.index, name='index'),
    # path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category,
         name='show_category'),
    path('add_category/', AddCategoryView.as_view(), name='add_category'),
    path('category/<slug:category_name_slug>/add_page', views.add_page,
         name='add_page'),
    # path('register/', views.register, name='register'),
    # path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    # path('logout/', views.user_logout, name='logout'),
    path('goto/', views.goto_url, name='goto'),
    path('register_profile/', views.register_profile, name='register_profile'),
    path('about/', AboutView.as_view(), name='about'),
    path('profile/<username>/', ProfileView.as_view(), name='profile'),
    path('profiles/', views.list_profiles, name='list_profiles'),

]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.urls import reverse


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')


urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
    path('accounts/register/',
         MyRegistrationView.as_view(),
         name='registration_register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):

    name = models.CharField(blank=True, max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField(blank=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Ingresar una categoria")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Ingresar un título")
    url = forms.URLField(max_length=200, help_text="Ingresar URL")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category', )

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        exclude = ('user',)

tango_with_django_project/rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from rango.models import Category
from rango.models import Page
from rango.models import UserProfile
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User



def index(request):
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    response = render(request, 'rango/index.html', context_dict)


    # template = 'rango/index.html'
    return response


# def about(request):
#     if request.session.test_cookie_worked():
#         print("TEST COOKIE WORKED!")
#         request.session.delete_test_cookie()
#     context_dict = {'mensajeAbout': "Este es el about"}
#     return render(request, 'rango/about.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context_dict)


# def add_category(request):
#     form = CategoryForm()
#
#     if request.method == 'POST':
#         form = CategoryForm(request.POST)
#
#         if form.is_valid():
#             form.save(commit=True)
#             return index(request)
#         else:
#             print(form.errors)
#     return render(request, 'rango/add_category.html', {'form': form})


class AddCategoryView(View):

    @method_decorator(login_required)
    def get(self, request):
        form = CategoryForm()
        return render(request, 'rango/add_category.html', {'form': form})

    @method_decorator(login_required)
    def post(self, request):
        form = CategoryForm()
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
        return render(request, 'rango/add_category.html', {'form': form})



def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)


# def register(request):
#
#     registered = False
#
#     if request.method == 'POST':
#         user_form = UserForm(data=request.POST)
#         profile_form = UserProfileForm(data=request.POST)
#         if user_form.is_valid() and profile_form.is_valid():
#             user = user_form.save()
#             user.set_password(user.password)
#             user.save()
#             profile = profile_form.save(commit=False)
#             profile.user = user
#             if 'picture' in request.FILES:
#                 profile.picture = request.FILES['picture']
#                 profile.save()
#                 registered = True
#         else:
#             print(user_form.errors, profile_form.erros)
#     else:
#         user_form = UserForm()
#         profile_form = UserProfileForm()
#     return render(request, 'rango/register.html', {'user_form': user_form,
#                                                    'profile_form': profile_form,
#                                                   'registered': registered})


# def user_login(request):
#
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(username=username, password=password)
#
#         if user:
#             if user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse('index'))
#             else:
#                 return HttpResponse("Tu cuenta está desactivada.")
#         else:
#             print("Invalid login details: {0}, {1}".format(username, password))
#             # return HttpResponse("Invalid login details supplied.")
#             return render(request, 'rango/login.html', {'error_message':'Invalid username and/or password entered. Try again'})
#     else:
#         return render(request, 'rango/login.html', {})


@login_required
def restricted(request):
    return HttpResponse("Since you're logged in, you can see this text!")


# @login_required
# def user_logout(request):
#     logout(request)
#     return HttpResponseRedirect(reverse('index'))


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def goto_url(request):
    page_id = None
    url = '/rango/'
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']

        try:
            page = Page.objects.get(id=page_id)
            page.views = page.views + 1
            page.save()
            url = page.url
        except:
            pass
    return redirect(url)


@login_required
def register_profile(request):
    form = UserProfileForm()
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
    if form.is_valid():
        user_profile = form.save(commit=False)
        user_profile.user = request.user
        user_profile.save()
        return redirect('index')
    else:
        print(form.errors)
        context_dict = {'form': form}
    return render(request, 'rango/profile_registration.html', context_dict)


class AboutView(View):
    def get(self, request):
        # view logic
        visitor_cookie_handler(request)
        return render(request, 'rango/about.html',
                      context={'visits': request.session['visits']})


class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return redirect('index')

        userprofile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'website': userprofile.website,
                                'picture': userprofile.picture})
        return (user, userprofile, form)

    @method_decorator(login_required)
    def get(self, request, username):
        (user, userprofile, form) = self.get_user_details(username)
        return render(request, 'rango/profile.html',
                               {'userprofile': userprofile,
                                   'selecteduser': user,
                                   'form': form})

    @method_decorator(login_required)
    def post(self, request, username):
        (user, userprofile, form) = self.get_user_details(username)
        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('profile', user.username)
        else:
            print(form.errors)
            return render(request, 'rango/profile.html',
                          {'userprofile': userprofile,
                           'selecteduser': user,
                           'form': form})


@login_required
def list_profiles(request):
    userprofile_list = UserProfile.objects.all()
    return render(request, 'rango/list_profiles.html',
                           {'userprofile_list': userprofile_list})

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {{ category.name}}
{% endblock %}

{% block body_block %}
    <h1>Acerca de....</h1>
    <strong>{{ mensajeAbout }}</strong><br />
    <img src="{{ MEDIA_URL}}Django_1.jpg" alt="Django_1">
    <br>
    <button class="btn btn-primary"
    onClick="alert('You clicked the button using inline JavaScript.');">
    Click Me - I run JavaScript
    </button>
    <button class="btn btn-primary" id="about-btn">
    Click Me - I'm JavaScript on Ice
    </button>
    <br>
    <p>This text is for a JQuery Example</p>
    <div id="msg">Hello - I'm here for a JQuery Example too</div>
{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends "rango/base.html" %}
{% block title %}
Add Category
{% endblock %}
{% block body_block %}
<div class="jumbotron p-4">
  <div class="container">
    <h1 class="jumbotron-heading">Add Category</h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <form role="form" id="page_form" method="post" action="/rango/category/{{category.slug}}/add_page/">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}
      {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br />
        {{ field }}<br />
      <div class="p-2"></div>
      {% endfor %}
      <br />
      <button class="btn btn-primary" type="submit" name="submit">
        Create Category
      </button>
      <div class="p-5"></div>
    </form>
  </div>
</div>
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends "rango/base.html" %}
{% block title %}
  Add Page
{% endblock %}
{% block body_block %}
<div class="jumbotron p-4">
  <div class="container">
    <h1 class="jumbotron-heading">Add Page to {{category.name}}</h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <form role="form" id="page_form" method="post" action="/rango/category/{{category.slug}}/add_page/">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}
      {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br />
        {{ field }}<br />
      <div class="p-2"></div>
      {% endfor %}
      <br />
      <button class="btn btn-primary" type="submit" name="submit">
        Add Page
      </button>
      <div class="p-5"></div>
    </form>
  </div>
</div>
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
{% load rango_extras %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v3.8.5">
  <link rel="icon" href="{% static 'images/favicon.ico' %}">
  <title>
    Rango - {% block title_block %}How to Tango with Django!{% endblock %}
  </title>

  <!-- Bootstrap core CSS -->
  <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
      <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
          <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item ">
          <a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a>
          </li>
          <li class="nav-item ">
          <a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a>
          </li>
          <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
          <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>

  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          {% block sidebar_block %}
            {% get_category_list category %}
          {% endblock %}
        </div>

      </nav>

      <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
        {% block body_block %}{% endblock %}

        <!-- FOOTER -->
        <footer>
          <p class="float-right"><a href="#">Back to top</a></p>
          <p>&copy; 2019 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
        </footer>
      </main>
    </div>
  </div>

  <!-- Bootstrap core JavaScript -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"  crossorigin="anonymous"></script>

  <script>
    window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')

  </script>
  <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
  <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
  <script src="{% static "js/rango-jquery.js" %}"></script>
</body>

</html>

tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {{ category.name}}
{% endblock %}

{% block body_block %}
        {% if category%}
          <h1>{{ category.name }}</h1>
          {% if pages %}
          <ul class="list-group">
            {% for page in pages %}

            <li class="list-group-item">
              <a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
              {% if page.views > 1 %}
                ({{ page.views }} views)
              {% elif page.views == 1 %}
                ({{ page.views }} view)
              {% endif %}
            </li>
            {% endfor %}
          </ul>
          {% else %}
            <strong>No hay páginas para esta categoría</strong>
          {% endif %}
          <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
        {% else %}
           No existe la categoría.
        {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/cats.html
<ul class="nav flex-column pt-6">

{% if cats %}
    {% for c in cats %}
    {% if c == act_cat %}
        <li  class="nav-item">
              <a  class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
				  <span data-feather="archive"></span>
				  {{ c.name }}</a>

        </li>
    {% else  %}
        <li class="nav-item">
            <a  class="nav-link" href="{% url 'rango:show_category' c.slug %}">
				<span data-feather="archive"></span>{{ c.name }}</a>
        </li>
    {% endif %}
{% endfor %}
{% else %}
    <li class="nav-item">No Categories Yet!</li>
{% endif %}
</ul>

tango_with_django_project/templates/rango/index.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}

{% load staticfiles %}
{% block body_block %}
<div class="jumbotron p-4">
  <div class="container">
    <h1 class="jumbotron-heading">Rango says...</h1>
    <div>
      <h2 class="h2">
        {% if user.is_authenticated %}
        Howdy {{ user.username }}!
        {% else %}
        Hey there partner!
        {% endif %}
      </h2>
      <strong>{{ boldmessage }}</strong>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card mb-6">
        <div class="card-body">
          <h2>Most Liked Categories</h2>
          <p class="card-text">
            {% if categories %}
            <ul class="list-group">
              {% for category in categories %}
              <li class="list-group-item">
                <a href="{% url 'rango:show_category' category.slug %}">
                  {{ category.name }}</a>
              </li>
              {% endfor %}
            </ul>
            {% else %}
            <strong>There are no categories present.</strong>
            {% endif %}
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card mb-6">
        <div class="card-body">
          <h2>Most Viewed Pages</h2>
          <p class="card-text">
            {% if pages %}
            <ul class="list-group">
              {% for page in pages %}
              <li class="list-group-item">
                <a href="{{ page.url }}">{{ page.title }}</a>
              </li>
              {% endfor %}
            </ul>
            {% else %}
            <strong>There are no pages present.</strong>
            {% endif %}
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<div>
  <img src="{% static "images/Django_Reinhardt.jpg" %}" alt="Picture of Django" />
</div>
{% endblock %}

tango_with_django_project/templates/rango/list_profiles.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}User Profiles{% endblock %}
{% block body_block %}
<div class="jumbotron p-4">
  <div class="container">
    <h1 class="jumbotron-heading">User Profiles</h1>
  </div>
</div>
<div class="container">
  <div class="row">
    {% if userprofile_list %}
    <div class="panel-heading">
      <!-- Display search results in an ordered list -->
      <div class="panel-body">
        <div class="list-group">
          {% for listuser in userprofile_list %}
          <div class="list-group-item">
            <h4 class="list-group-item-heading">
              <a href="{% url 'rango:profile' listuser.user.username %}">
                {{ listuser.user.username }}</a>
            </h4>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    {% else %}
    <p>There are no users for the site.</p>
    {% endif %}
  </div>
</div>
{% endblock %}

tango_with_django_project/templates/rango/login.html
{% extends 'rango/base.html'%}
{% load staticfiles %}

{% block title_block %}
Login
{% endblock %}

{% block body_block %}
<link href="https://getbootstrap.com/docs/4.0/examples/signin/signin.css" rel="stylesheet">
<div class="jumbotron p-4">
  <h1 class="jumbotron-heading">Login</h1>
</div>
<div class="container">
  <form class="form-signin" role="form" method="post" action=".">
    {% csrf_token %}
    <h2 class="form-signin-heading">Please sign in</h2>
    <label for="inputUsername" class="sr-only">Username</label>
    <input type="text" name="username" id="id_username" class="form-control" placeholder="Username" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit" />Sign in</button>
  </form>
</div>
{% endblock %}

tango_with_django_project/templates/rango/profile.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}{{ selecteduser.username }} Profile{% endblock %}
{% block body_block %}
<div class="jumbotron p-4">
  <div class="container">
    <h1 class="jumbotron-heading">{{selecteduser.username}} Profile</h1>
  </div>
</div>
<div class="container">
  <div class="row">

    {% if userprofile.picture %}

      <img src="{{ MEDIA_URL }}{{userprofile.picture }}" width="300" height="300" alt="{{selecteduser.username}}" />
    {% else %}
      <img width="256" height="256" src="http://lorempixel.com/256/256/people/"/>
    {% endif %}


    <br/>
    <div>
      {% if selecteduser.username == user.username %}
      <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
      </form>
      {% else %}
      <p><strong>Website:</strong> <a href="{{userprofile.website}}">
          {{userprofile.website}}</a></p>
      {% endif %}
    </div>
    <div id="edit_profile"></div>
  </div>
</div>

{% endblock %}

tango_with_django_project/templates/rango/profile_registration.html
{% extends "rango/base.html" %}
{% block title_block %}
  Registration - Step 2
{% endblock %}
{% block body_block %}
  <div class="jumbotron p-4">
  <div class="container">
    <h1 class="jumbotron-heading">Registration - Step 2</h1>
    </div>
  </div>
  <div class="container">
  <div class="row">
    <form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
  </div>
  </div>
{% endblock %}

tango_with_django_project/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Register
{% endblock %}

{% block body_block %}
     <h1> Registración </h1>
     {% if registered %}
       <strong>Gracias por registrarte!</strong>
     {% else %}
       <strong>Registrate acá:</strong>
       <form id="user_form" method="post" action="{% url 'rango:register' %}"
       enctype="multipart/form-data">

       {% csrf_token %}

       {{ user_form.as_p}}
       {{ profile_form.as_p}}
       <input type="submit" name="submit" value="Register" />
       </form>
     {% endif %}
 {% endblock %}

tango_with_django_project/templates/rango/vieja_base.html
<!-- <!DOCTYPE html>
{% load rango_template_tags %}

<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>
    Rango
    {% block title_etc %}
    | How to Tango with Django
    {% endblock %}

  </title>
</head>


<body>
  <div>
    {% block sideetc_block %}
    {% get_category_list category %}
    {% endblock %}
  </div>
  <div>
    {% block body_betc %}
    {% endblock %}
  </div>
  <hr />
  <div>
    <ul>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
        <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
        {% else %}
        <li><a href="{% url 'auth_login' %}">Sign In</a></li>
        <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
        {% endif %}
        <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
        <li><a href="{% url 'rango:about' %}">About</a></li>
        <li><a href="{% url 'rango:index' %}">Index</a></li>
      </ul>
    </ul>
  </div>


</body>

</html> -->

tango_with_django_project/templates/rango/viejo_cats.html
<ul class="nav flex-column">
  {% if cats %}
  {% for c in cats %}
  {% if c == act_cat %}
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
      <span data-feather="archive"></span>
      { c.name }}</a>
  </li>
  {% else %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
      <span data-feather="archive"></span>{{ c.name }}</a>
  </li>
  {% endif %}
  {% endfor %}
  {% else %}
  <li class="nav-item">No Categories Yet!</li>
  {% endif %}
</ul>